"""Mock player data with real 2025/26 season statistics."""

import hashlib
import os

# ---- 赛事权重（与 scoring.py 保持同步） ----
W = {
    "world_cup": 100.0,
    "continental_cup": 80.0,
    "confederations_cup": 30.0,
    "nations_league": 35.0,
    "champions_league": 75.0,
    "club_world_cup": 45.0,
    "europa_league": 50.0,
    "top5_league": 60.0,
    "domestic_cup": 40.0,
    "domestic_super_cup": 25.0,
    "uefa_super_cup": 30.0,
}

# ---- 个人奖项权重（与 scoring.py 保持同步） ----
A = {
    "ballon_dor": 100.0,
    "fifa_best": 95.0,
    "uefa_best": 85.0,
    "european_golden_boot": 70.0,
    "world_cup_golden_boot": 65.0,
    "world_cup_golden_ball": 75.0,
    "ucl_top_scorer": 55.0,
    "league_top_scorer": 50.0,
    "domestic_cup_top_scorer": 30.0,
    "yashin_award": 80.0,
    "fifa_best_gk": 75.0,
    "league_golden_glove": 45.0,
    "pfa_player_of_year": 55.0,
    "golden_boy": 40.0,
    "kopa_trophy": 45.0,
    "best_young_player": 35.0,
    "team_of_season": 35.0,
    "player_of_month": 15.0,
}

MOCK_PLAYERS = [
    # ===================== 前锋 FORWARD =====================
    {
        "name": "埃尔林·哈兰德",
        "name_en": "Erling Haaland",
        "position": "forward",
        "nationality": "Norway",
        "age": 26,
        "market_value_euro": 220000000,
        "current_club": "Manchester City",
        "club_league": "Premier League",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Norway",
        "club_strength_score": 95.0,
        "national_team_strength_score": 60.0,
        "image_url": "/static/avatars/erling-haaland.png",
        "stats": {
            "appearances": 45, "minutes_played": 3850, "goals": 35, "assists": 8,
            "shots_total": 140, "shots_on_target": 65, "pass_accuracy": 72.0,
            "key_passes": 40, "tackles": 12, "interceptions": 8, "clearances": 15,
            "blocks": 10, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 22, "aerial_duels_won": 80, "fouls_committed": 30,
            "fouls_drawn": 55, "yellow_cards": 4, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "英超冠军", "honor_type": "club", "competition_name": "Premier League", "competition_weight": W["top5_league"], "count": 2, "year": "2023/2024"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2022/2023"},
            {"honor_name": "世俱杯冠军", "honor_type": "club", "competition_name": "FIFA Club World Cup", "competition_weight": W["club_world_cup"], "count": 1, "year": "2023"},
            {"honor_name": "足总杯冠军", "honor_type": "club", "competition_name": "FA Cup", "competition_weight": W["domestic_cup"], "count": 1, "year": "2022/2023"},
        ],
        "awards": [
            {"award_name": "欧洲金靴", "award_weight": A["european_golden_boot"], "count": 1, "year": "2022/2023"},
            {"award_name": "英超金靴", "award_weight": A["league_top_scorer"], "count": 3, "year": "2025/2026"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 3, "year": "2025/2026"},
        ],
    },
    {
        "name": "基利安·姆巴佩",
        "name_en": "Kylian Mbappé",
        "position": "forward",
        "nationality": "France",
        "age": 27,
        "market_value_euro": 200000000,
        "current_club": "Real Madrid",
        "club_league": "La Liga",
        "is_captain": True,
        "is_vice_captain": True,
        "national_team": "France",
        "club_strength_score": 97.0,
        "national_team_strength_score": 92.0,
        "image_url": "/static/avatars/kylian-mbapp.png",
        "stats": {
            "appearances": 44, "minutes_played": 3700, "goals": 30, "assists": 6,
            "shots_total": 150, "shots_on_target": 70, "pass_accuracy": 80.0,
            "key_passes": 50, "tackles": 20, "interceptions": 12, "clearances": 5,
            "blocks": 8, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 80, "aerial_duels_won": 20, "fouls_committed": 28,
            "fouls_drawn": 65, "yellow_cards": 5, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "世界杯冠军", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2018"},
            {"honor_name": "世界杯四强", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2026"},
            {"honor_name": "欧国联冠军", "honor_type": "national_team", "competition_name": "UEFA Nations League", "competition_weight": W["nations_league"], "count": 1, "year": "2021"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2024/2025"},
            {"honor_name": "西甲冠军", "honor_type": "club", "competition_name": "La Liga", "competition_weight": W["top5_league"], "count": 1, "year": "2024/2025"},
            {"honor_name": "法甲冠军", "honor_type": "club", "competition_name": "Ligue 1", "competition_weight": W["top5_league"], "count": 6, "year": "2017-2023"},
        ],
        "awards": [
            {"award_name": "世界杯金靴", "award_weight": A["world_cup_golden_boot"], "count": 1, "year": "2026"},
            {"award_name": "世界杯金球奖", "award_weight": A["world_cup_golden_ball"], "count": 1, "year": "2022"},
            {"award_name": "联赛金靴", "award_weight": A["league_top_scorer"], "count": 6, "year": "2025/2026"},
            {"award_name": "科帕奖", "award_weight": A["kopa_trophy"], "count": 1, "year": "2018"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 5, "year": "2025/2026"},
        ],
    },
    {
        "name": "哈里·凯恩",
        "name_en": "Harry Kane",
        "position": "forward",
        "nationality": "England",
        "age": 32,
        "market_value_euro": 60000000,
        "current_club": "Bayern Munich",
        "club_league": "Bundesliga",
        "is_captain": True,
        "is_vice_captain": False,
        "national_team": "England",
        "club_strength_score": 90.0,
        "national_team_strength_score": 88.0,
        "image_url": "/static/avatars/harry-kane.png",
        "stats": {
            "appearances": 50, "minutes_played": 4000, "goals": 45, "assists": 8,
            "shots_total": 180, "shots_on_target": 95, "pass_accuracy": 76.0,
            "key_passes": 55, "tackles": 12, "interceptions": 8, "clearances": 20,
            "blocks": 12, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 25, "aerial_duels_won": 90, "fouls_committed": 35,
            "fouls_drawn": 60, "yellow_cards": 3, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "世界杯季军", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2026"},
            {"honor_name": "德甲冠军", "honor_type": "club", "competition_name": "Bundesliga", "competition_weight": W["top5_league"], "count": 2, "year": "2025/2026"},
        ],
        "awards": [
            {"award_name": "欧洲金靴", "award_weight": A["european_golden_boot"], "count": 1, "year": "2025/2026"},
            {"award_name": "德甲金靴", "award_weight": A["league_top_scorer"], "count": 2, "year": "2025/2026"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 4, "year": "2025/2026"},
        ],
    },
    {
        "name": "罗伯特·莱万多夫斯基",
        "name_en": "Robert Lewandowski",
        "position": "forward",
        "nationality": "Poland",
        "age": 37,
        "market_value_euro": 7000000,
        "current_club": "Barcelona",
        "club_league": "La Liga",
        "is_captain": True,
        "is_vice_captain": True,
        "national_team": "Poland",
        "club_strength_score": 93.0,
        "national_team_strength_score": 70.0,
        "image_url": "/static/avatars/robert-lewandowski.png",
        "stats": {
            "appearances": 42, "minutes_played": 3000, "goals": 18, "assists": 5,
            "shots_total": 100, "shots_on_target": 45, "pass_accuracy": 77.0,
            "key_passes": 32, "tackles": 8, "interceptions": 5, "clearances": 10,
            "blocks": 6, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 15, "aerial_duels_won": 55, "fouls_committed": 22,
            "fouls_drawn": 35, "yellow_cards": 4, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2019/2020"},
            {"honor_name": "西甲冠军", "honor_type": "club", "competition_name": "La Liga", "competition_weight": W["top5_league"], "count": 2, "year": "2025/2026"},
            {"honor_name": "德甲冠军", "honor_type": "club", "competition_name": "Bundesliga", "competition_weight": W["top5_league"], "count": 10, "year": "2013-2022"},
            {"honor_name": "世俱杯冠军", "honor_type": "club", "competition_name": "FIFA Club World Cup", "competition_weight": W["club_world_cup"], "count": 1, "year": "2020"},
        ],
        "awards": [
            {"award_name": "欧洲金靴", "award_weight": A["european_golden_boot"], "count": 2, "year": "2020/2021"},
            {"award_name": "国际足联最佳球员", "award_weight": A["fifa_best"], "count": 1, "year": "2020"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 6, "year": "2025/2026"},
        ],
    },
    {
        "name": "维克托·奥斯梅恩",
        "name_en": "Victor Osimhen",
        "position": "forward",
        "nationality": "Nigeria",
        "age": 27,
        "market_value_euro": 75000000,
        "current_club": "Galatasaray",
        "club_league": "Süper Lig",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Nigeria",
        "club_strength_score": 72.0,
        "national_team_strength_score": 65.0,
        "image_url": "/static/avatars/victor-osimhen.png",
        "stats": {
            "appearances": 46, "minutes_played": 3800, "goals": 35, "assists": 6,
            "shots_total": 150, "shots_on_target": 70, "pass_accuracy": 70.0,
            "key_passes": 28, "tackles": 18, "interceptions": 10, "clearances": 20,
            "blocks": 12, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 30, "aerial_duels_won": 95, "fouls_committed": 50,
            "fouls_drawn": 70, "yellow_cards": 7, "red_cards": 1,
        },
        "honors": [
            {"honor_name": "意甲冠军", "honor_type": "club", "competition_name": "Serie A", "competition_weight": W["top5_league"], "count": 1, "year": "2022/2023"},
        ],
        "awards": [
            {"award_name": "意甲金靴", "award_weight": A["league_top_scorer"], "count": 1, "year": "2022/2023"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 2, "year": "2025/2026"},
        ],
    },
    {
        "name": "亚历山大·拉卡泽特",
        "name_en": "Alexandre Lacazette",
        "position": "forward",
        "nationality": "France",
        "age": 34,
        "market_value_euro": 8000000,
        "current_club": "Lyon",
        "club_league": "Ligue 1",
        "is_captain": True,
        "is_vice_captain": False,
        "national_team": "France",
        "club_strength_score": 68.0,
        "national_team_strength_score": 88.0,
        "image_url": "/static/avatars/alexandre-lacazette.png",
        "stats": {
            "appearances": 36, "minutes_played": 2800, "goals": 15, "assists": 6,
            "shots_total": 80, "shots_on_target": 35, "pass_accuracy": 78.0,
            "key_passes": 35, "tackles": 15, "interceptions": 10, "clearances": 12,
            "blocks": 8, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 22, "aerial_duels_won": 30, "fouls_committed": 40,
            "fouls_drawn": 45, "yellow_cards": 5, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "法甲冠军", "honor_type": "club", "competition_name": "Ligue 1", "competition_weight": W["top5_league"], "count": 1, "year": "2021/2022"},
        ],
        "awards": [
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 1, "year": "2021/2022"},
        ],
    },

    # ===================== 中场 MIDFIELDER =====================
    {
        "name": "凯文·德布劳内",
        "name_en": "Kevin De Bruyne",
        "position": "midfielder",
        "nationality": "Belgium",
        "age": 35,
        "market_value_euro": 8000000,
        "current_club": "Manchester City",
        "club_league": "Premier League",
        "is_captain": False,
        "is_vice_captain": True,
        "national_team": "Belgium",
        "club_strength_score": 95.0,
        "national_team_strength_score": 82.0,
        "image_url": "/static/avatars/kevin-de-bruyne.png",
        "stats": {
            "appearances": 32, "minutes_played": 2200, "goals": 5, "assists": 14,
            "shots_total": 45, "shots_on_target": 18, "pass_accuracy": 85.0,
            "key_passes": 85, "tackles": 25, "interceptions": 18, "clearances": 10,
            "blocks": 12, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 28, "aerial_duels_won": 10, "fouls_committed": 22,
            "fouls_drawn": 30, "yellow_cards": 3, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "英超冠军", "honor_type": "club", "competition_name": "Premier League", "competition_weight": W["top5_league"], "count": 5, "year": "2017-2024"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2022/2023"},
            {"honor_name": "足总杯冠军", "honor_type": "club", "competition_name": "FA Cup", "competition_weight": W["domestic_cup"], "count": 2, "year": "2022/2023"},
        ],
        "awards": [
            {"award_name": "PFA年度最佳球员", "award_weight": A["pfa_player_of_year"], "count": 2, "year": "2019/2020"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 5, "year": "2025/2026"},
        ],
    },
    {
        "name": "裘德·贝林厄姆",
        "name_en": "Jude Bellingham",
        "position": "midfielder",
        "nationality": "England",
        "age": 23,
        "market_value_euro": 160000000,
        "current_club": "Real Madrid",
        "club_league": "La Liga",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "England",
        "club_strength_score": 97.0,
        "national_team_strength_score": 88.0,
        "image_url": "/static/avatars/jude-bellingham.png",
        "stats": {
            "appearances": 40, "minutes_played": 3000, "goals": 10, "assists": 6,
            "shots_total": 75, "shots_on_target": 35, "pass_accuracy": 86.0,
            "key_passes": 60, "tackles": 45, "interceptions": 30, "clearances": 20,
            "blocks": 28, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 50, "aerial_duels_won": 30, "fouls_committed": 40,
            "fouls_drawn": 55, "yellow_cards": 5, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "世界杯季军", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2026"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2023/2024"},
            {"honor_name": "西甲冠军", "honor_type": "club", "competition_name": "La Liga", "competition_weight": W["top5_league"], "count": 2, "year": "2024/2025"},
        ],
        "awards": [
            {"award_name": "科帕奖", "award_weight": A["kopa_trophy"], "count": 1, "year": "2023"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 3, "year": "2025/2026"},
        ],
    },
    {
        "name": "罗德里",
        "name_en": "Rodri",
        "position": "midfielder",
        "nationality": "Spain",
        "age": 30,
        "market_value_euro": 55000000,
        "current_club": "Manchester City",
        "club_league": "Premier League",
        "is_captain": True,
        "is_vice_captain": False,
        "national_team": "Spain",
        "club_strength_score": 95.0,
        "national_team_strength_score": 92.0,
        "image_url": "/static/avatars/rodri.png",
        "stats": {
            "appearances": 28, "minutes_played": 1800, "goals": 1, "assists": 2,
            "shots_total": 20, "shots_on_target": 8, "pass_accuracy": 92.0,
            "key_passes": 30, "tackles": 42, "interceptions": 35, "clearances": 25,
            "blocks": 30, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 15, "aerial_duels_won": 25, "fouls_committed": 28,
            "fouls_drawn": 20, "yellow_cards": 5, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "世界杯冠军", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2026"},
            {"honor_name": "欧洲杯冠军", "honor_type": "national_team", "competition_name": "UEFA European Championship", "competition_weight": W["continental_cup"], "count": 1, "year": "2024"},
            {"honor_name": "英超冠军", "honor_type": "club", "competition_name": "Premier League", "competition_weight": W["top5_league"], "count": 4, "year": "2020-2024"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2022/2023"},
        ],
        "awards": [
            {"award_name": "世界杯金球奖", "award_weight": A["world_cup_golden_ball"], "count": 1, "year": "2026"},
            {"award_name": "金球奖", "award_weight": A["ballon_dor"], "count": 1, "year": "2024"},
            {"award_name": "国际足联最佳球员", "award_weight": A["fifa_best"], "count": 1, "year": "2024"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 4, "year": "2025/2026"},
        ],
    },
    {
        "name": "卢卡·莫德里奇",
        "name_en": "Luka Modrić",
        "position": "midfielder",
        "nationality": "Croatia",
        "age": 40,
        "market_value_euro": 3500000,
        "current_club": "Real Madrid",
        "club_league": "La Liga",
        "is_captain": True,
        "is_vice_captain": False,
        "national_team": "Croatia",
        "club_strength_score": 97.0,
        "national_team_strength_score": 78.0,
        "image_url": "/static/avatars/luka-modri.png",
        "stats": {
            "appearances": 35, "minutes_played": 2000, "goals": 2, "assists": 5,
            "shots_total": 25, "shots_on_target": 10, "pass_accuracy": 89.0,
            "key_passes": 50, "tackles": 30, "interceptions": 20, "clearances": 10,
            "blocks": 15, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 25, "aerial_duels_won": 10, "fouls_committed": 20,
            "fouls_drawn": 25, "yellow_cards": 4, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "世界杯亚军", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2018"},
            {"honor_name": "世界杯季军", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2022"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 5, "year": "2014-2022"},
            {"honor_name": "西甲冠军", "honor_type": "club", "competition_name": "La Liga", "competition_weight": W["top5_league"], "count": 5, "year": "2025/2026"},
            {"honor_name": "世俱杯冠军", "honor_type": "club", "competition_name": "FIFA Club World Cup", "competition_weight": W["club_world_cup"], "count": 4, "year": "2016-2022"},
        ],
        "awards": [
            {"award_name": "金球奖", "award_weight": A["ballon_dor"], "count": 1, "year": "2018"},
            {"award_name": "国际足联最佳球员", "award_weight": A["fifa_best"], "count": 1, "year": "2018"},
            {"award_name": "欧足联最佳球员", "award_weight": A["uefa_best"], "count": 1, "year": "2017/2018"},
        ],
    },
    {
        "name": "贾马尔·穆西亚拉",
        "name_en": "Jamal Musiala",
        "position": "midfielder",
        "nationality": "Germany",
        "age": 23,
        "market_value_euro": 140000000,
        "current_club": "Bayern Munich",
        "club_league": "Bundesliga",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Germany",
        "club_strength_score": 90.0,
        "national_team_strength_score": 85.0,
        "image_url": "/static/avatars/jamal-musiala.png",
        "stats": {
            "appearances": 48, "minutes_played": 3800, "goals": 18, "assists": 14,
            "shots_total": 95, "shots_on_target": 40, "pass_accuracy": 87.0,
            "key_passes": 65, "tackles": 35, "interceptions": 25, "clearances": 12,
            "blocks": 20, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 70, "aerial_duels_won": 18, "fouls_committed": 30,
            "fouls_drawn": 50, "yellow_cards": 3, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "德甲冠军", "honor_type": "club", "competition_name": "Bundesliga", "competition_weight": W["top5_league"], "count": 4, "year": "2025/2026"},
            {"honor_name": "欧洲杯四强", "honor_type": "national_team", "competition_name": "UEFA European Championship", "competition_weight": W["continental_cup"], "count": 1, "year": "2024"},
        ],
        "awards": [
            {"award_name": "科帕奖", "award_weight": A["kopa_trophy"], "count": 1, "year": "2024"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 3, "year": "2025/2026"},
        ],
    },
    {
        "name": "费德里科·基耶萨",
        "name_en": "Federico Chiesa",
        "position": "midfielder",
        "nationality": "Italy",
        "age": 28,
        "market_value_euro": 20000000,
        "current_club": "Liverpool",
        "club_league": "Premier League",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Italy",
        "club_strength_score": 88.0,
        "national_team_strength_score": 80.0,
        "image_url": "/static/avatars/federico-chiesa.png",
        "stats": {
            "appearances": 32, "minutes_played": 1800, "goals": 7, "assists": 5,
            "shots_total": 55, "shots_on_target": 22, "pass_accuracy": 79.0,
            "key_passes": 35, "tackles": 22, "interceptions": 14, "clearances": 6,
            "blocks": 10, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 45, "aerial_duels_won": 12, "fouls_committed": 28,
            "fouls_drawn": 40, "yellow_cards": 4, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "欧洲杯冠军", "honor_type": "national_team", "competition_name": "UEFA European Championship", "competition_weight": W["continental_cup"], "count": 1, "year": "2020"},
        ],
        "awards": [
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 1, "year": "2020/2021"},
        ],
    },

    # ===================== 后卫 DEFENDER =====================
    {
        "name": "维吉尔·范迪克",
        "name_en": "Virgil van Dijk",
        "position": "defender",
        "nationality": "Netherlands",
        "age": 35,
        "market_value_euro": 15000000,
        "current_club": "Liverpool",
        "club_league": "Premier League",
        "is_captain": True,
        "is_vice_captain": False,
        "national_team": "Netherlands",
        "club_strength_score": 85.0,
        "national_team_strength_score": 82.0,
        "image_url": "/static/avatars/virgil-van-dijk.png",
        "stats": {
            "appearances": 40, "minutes_played": 3600, "goals": 6, "assists": 1,
            "shots_total": 35, "shots_on_target": 12, "pass_accuracy": 90.0,
            "key_passes": 15, "tackles": 28, "interceptions": 30, "clearances": 320,
            "blocks": 25, "saves": 0, "clean_sheets": 10, "goals_conceded": 0,
            "dribbles_completed": 8, "aerial_duels_won": 130, "fouls_committed": 22,
            "fouls_drawn": 15, "yellow_cards": 4, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2018/2019"},
            {"honor_name": "英超冠军", "honor_type": "club", "competition_name": "Premier League", "competition_weight": W["top5_league"], "count": 1, "year": "2019/2020"},
            {"honor_name": "世俱杯冠军", "honor_type": "club", "competition_name": "FIFA Club World Cup", "competition_weight": W["club_world_cup"], "count": 1, "year": "2019"},
            {"honor_name": "欧国联亚军", "honor_type": "national_team", "competition_name": "UEFA Nations League", "competition_weight": W["nations_league"], "count": 1, "year": "2019"},
        ],
        "awards": [
            {"award_name": "欧足联最佳球员", "award_weight": A["uefa_best"], "count": 1, "year": "2018/2019"},
            {"award_name": "PFA年度最佳球员", "award_weight": A["pfa_player_of_year"], "count": 1, "year": "2018/2019"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 4, "year": "2025/2026"},
        ],
    },
    {
        "name": "鲁本·迪亚斯",
        "name_en": "Rúben Dias",
        "position": "defender",
        "nationality": "Portugal",
        "age": 29,
        "market_value_euro": 55000000,
        "current_club": "Manchester City",
        "club_league": "Premier League",
        "is_captain": False,
        "is_vice_captain": True,
        "national_team": "Portugal",
        "club_strength_score": 95.0,
        "national_team_strength_score": 86.0,
        "image_url": "/static/avatars/r-ben-dias.png",
        "stats": {
            "appearances": 32, "minutes_played": 2800, "goals": 2, "assists": 1,
            "shots_total": 20, "shots_on_target": 8, "pass_accuracy": 93.0,
            "key_passes": 10, "tackles": 32, "interceptions": 28, "clearances": 140,
            "blocks": 40, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 5, "aerial_duels_won": 80, "fouls_committed": 20,
            "fouls_drawn": 12, "yellow_cards": 4, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "英超冠军", "honor_type": "club", "competition_name": "Premier League", "competition_weight": W["top5_league"], "count": 3, "year": "2020-2024"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2022/2023"},
            {"honor_name": "欧国联冠军", "honor_type": "national_team", "competition_name": "UEFA Nations League", "competition_weight": W["nations_league"], "count": 1, "year": "2019"},
        ],
        "awards": [
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 3, "year": "2025/2026"},
        ],
    },
    {
        "name": "安东尼奥·吕迪格",
        "name_en": "Antonio Rüdiger",
        "position": "defender",
        "nationality": "Germany",
        "age": 33,
        "market_value_euro": 12000000,
        "current_club": "Real Madrid",
        "club_league": "La Liga",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Germany",
        "club_strength_score": 97.0,
        "national_team_strength_score": 85.0,
        "image_url": "/static/avatars/antonio-r-diger.png",
        "stats": {
            "appearances": 38, "minutes_played": 3300, "goals": 2, "assists": 1,
            "shots_total": 25, "shots_on_target": 10, "pass_accuracy": 88.0,
            "key_passes": 12, "tackles": 40, "interceptions": 32, "clearances": 150,
            "blocks": 45, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 10, "aerial_duels_won": 100, "fouls_committed": 45,
            "fouls_drawn": 20, "yellow_cards": 8, "red_cards": 1,
        },
        "honors": [
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 2, "year": "2020/2021,2023/2024"},
            {"honor_name": "西甲冠军", "honor_type": "club", "competition_name": "La Liga", "competition_weight": W["top5_league"], "count": 2, "year": "2024/2025"},
            {"honor_name": "欧洲杯冠军", "honor_type": "national_team", "competition_name": "UEFA European Championship", "competition_weight": W["continental_cup"], "count": 1, "year": "2024"},
        ],
        "awards": [
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 3, "year": "2025/2026"},
        ],
    },
    {
        "name": "马尔基尼奥斯",
        "name_en": "Marquinhos",
        "position": "defender",
        "nationality": "Brazil",
        "age": 31,
        "market_value_euro": 28000000,
        "current_club": "Paris Saint-Germain",
        "club_league": "Ligue 1",
        "is_captain": True,
        "is_vice_captain": False,
        "national_team": "Brazil",
        "club_strength_score": 88.0,
        "national_team_strength_score": 89.0,
        "image_url": "/static/avatars/marquinhos.png",
        "stats": {
            "appearances": 42, "minutes_played": 3700, "goals": 2, "assists": 1,
            "shots_total": 20, "shots_on_target": 7, "pass_accuracy": 94.0,
            "key_passes": 12, "tackles": 38, "interceptions": 35, "clearances": 120,
            "blocks": 35, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 12, "aerial_duels_won": 80, "fouls_committed": 25,
            "fouls_drawn": 18, "yellow_cards": 4, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 2, "year": "2025/2026"},
            {"honor_name": "法甲冠军", "honor_type": "club", "competition_name": "Ligue 1", "competition_weight": W["top5_league"], "count": 8, "year": "2025/2026"},
            {"honor_name": "美洲杯冠军", "honor_type": "national_team", "competition_name": "Copa América", "competition_weight": W["continental_cup"], "count": 1, "year": "2019"},
        ],
        "awards": [
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 3, "year": "2025/2026"},
        ],
    },
    {
        "name": "特奥·埃尔南德斯",
        "name_en": "Theo Hernández",
        "position": "defender",
        "nationality": "France",
        "age": 28,
        "market_value_euro": 20000000,
        "current_club": "Al-Hilal",
        "club_league": "Saudi Pro League",
        "is_captain": False,
        "is_vice_captain": True,
        "national_team": "France",
        "club_strength_score": 75.0,
        "national_team_strength_score": 88.0,
        "image_url": "/static/avatars/theo-hern-ndez.png",
        "stats": {
            "appearances": 44, "minutes_played": 3800, "goals": 5, "assists": 7,
            "shots_total": 55, "shots_on_target": 20, "pass_accuracy": 85.0,
            "key_passes": 50, "tackles": 55, "interceptions": 35, "clearances": 70,
            "blocks": 35, "saves": 0, "clean_sheets": 0, "goals_conceded": 0,
            "dribbles_completed": 65, "aerial_duels_won": 45, "fouls_committed": 45,
            "fouls_drawn": 40, "yellow_cards": 7, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "意甲冠军", "honor_type": "club", "competition_name": "Serie A", "competition_weight": W["top5_league"], "count": 1, "year": "2021/2022"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2024/2025"},
            {"honor_name": "世界杯四强", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2026"},
        ],
        "awards": [
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 2, "year": "2025/2026"},
        ],
    },

    # ===================== 门将 GOALKEEPER =====================
    {
        "name": "蒂博·库尔图瓦",
        "name_en": "Thibaut Courtois",
        "position": "goalkeeper",
        "nationality": "Belgium",
        "age": 34,
        "market_value_euro": 15000000,
        "current_club": "Real Madrid",
        "club_league": "La Liga",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Belgium",
        "club_strength_score": 97.0,
        "national_team_strength_score": 82.0,
        "image_url": "/static/avatars/thibaut-courtois.png",
        "stats": {
            "appearances": 45, "minutes_played": 4050, "goals": 0, "assists": 0,
            "shots_total": 0, "shots_on_target": 0, "pass_accuracy": 80.0,
            "key_passes": 2, "tackles": 0, "interceptions": 0, "clearances": 25,
            "blocks": 0, "saves": 100, "clean_sheets": 18, "goals_conceded": 42,
            "dribbles_completed": 0, "aerial_duels_won": 12, "fouls_committed": 1,
            "fouls_drawn": 3, "yellow_cards": 1, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 2, "year": "2018/2019,2021/2022"},
            {"honor_name": "西甲冠军", "honor_type": "club", "competition_name": "La Liga", "competition_weight": W["top5_league"], "count": 3, "year": "2024/2025"},
            {"honor_name": "世俱杯冠军", "honor_type": "club", "competition_name": "FIFA Club World Cup", "competition_weight": W["club_world_cup"], "count": 2, "year": "2019,2022"},
        ],
        "awards": [
            {"award_name": "雅辛奖", "award_weight": A["yashin_award"], "count": 1, "year": "2022"},
            {"award_name": "FIFA最佳门将", "award_weight": A["fifa_best_gk"], "count": 1, "year": "2022"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 3, "year": "2025/2026"},
        ],
    },
    {
        "name": "阿利松",
        "name_en": "Alisson",
        "position": "goalkeeper",
        "nationality": "Brazil",
        "age": 33,
        "market_value_euro": 15000000,
        "current_club": "Liverpool",
        "club_league": "Premier League",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Brazil",
        "club_strength_score": 85.0,
        "national_team_strength_score": 89.0,
        "image_url": "/static/avatars/alisson.png",
        "stats": {
            "appearances": 30, "minutes_played": 2700, "goals": 0, "assists": 0,
            "shots_total": 0, "shots_on_target": 0, "pass_accuracy": 83.0,
            "key_passes": 3, "tackles": 0, "interceptions": 0, "clearances": 22,
            "blocks": 0, "saves": 75, "clean_sheets": 10, "goals_conceded": 30,
            "dribbles_completed": 0, "aerial_duels_won": 15, "fouls_committed": 1,
            "fouls_drawn": 2, "yellow_cards": 1, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2018/2019"},
            {"honor_name": "英超冠军", "honor_type": "club", "competition_name": "Premier League", "competition_weight": W["top5_league"], "count": 1, "year": "2019/2020"},
            {"honor_name": "美洲杯冠军", "honor_type": "national_team", "competition_name": "Copa América", "competition_weight": W["continental_cup"], "count": 1, "year": "2019"},
            {"honor_name": "世俱杯冠军", "honor_type": "club", "competition_name": "FIFA Club World Cup", "competition_weight": W["club_world_cup"], "count": 1, "year": "2019"},
        ],
        "awards": [
            {"award_name": "雅辛奖", "award_weight": A["yashin_award"], "count": 1, "year": "2019"},
            {"award_name": "FIFA最佳门将", "award_weight": A["fifa_best_gk"], "count": 1, "year": "2019"},
            {"award_name": "联赛金手套", "award_weight": A["league_golden_glove"], "count": 1, "year": "2018/2019"},
        ],
    },
    {
        "name": "埃德森",
        "name_en": "Ederson",
        "position": "goalkeeper",
        "nationality": "Brazil",
        "age": 32,
        "market_value_euro": 10000000,
        "current_club": "Fenerbahçe",
        "club_league": "Süper Lig",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Brazil",
        "club_strength_score": 70.0,
        "national_team_strength_score": 89.0,
        "image_url": "/static/avatars/ederson.png",
        "stats": {
            "appearances": 22, "minutes_played": 1980, "goals": 0, "assists": 0,
            "shots_total": 0, "shots_on_target": 0, "pass_accuracy": 86.0,
            "key_passes": 2, "tackles": 0, "interceptions": 0, "clearances": 15,
            "blocks": 0, "saves": 50, "clean_sheets": 12, "goals_conceded": 28,
            "dribbles_completed": 0, "aerial_duels_won": 6, "fouls_committed": 1,
            "fouls_drawn": 2, "yellow_cards": 1, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "英超冠军", "honor_type": "club", "competition_name": "Premier League", "competition_weight": W["top5_league"], "count": 5, "year": "2017-2024"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 1, "year": "2022/2023"},
            {"honor_name": "美洲杯冠军", "honor_type": "national_team", "competition_name": "Copa América", "competition_weight": W["continental_cup"], "count": 1, "year": "2019"},
            {"honor_name": "世俱杯冠军", "honor_type": "club", "competition_name": "FIFA Club World Cup", "competition_weight": W["club_world_cup"], "count": 1, "year": "2023"},
        ],
        "awards": [
            {"award_name": "联赛金手套", "award_weight": A["league_golden_glove"], "count": 3, "year": "2019/2020"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 2, "year": "2020/2021"},
        ],
    },
    {
        "name": "吉安路易吉·多纳鲁马",
        "name_en": "Gianluigi Donnarumma",
        "position": "goalkeeper",
        "nationality": "Italy",
        "age": 27,
        "market_value_euro": 45000000,
        "current_club": "Paris Saint-Germain",
        "club_league": "Ligue 1",
        "is_captain": False,
        "is_vice_captain": False,
        "national_team": "Italy",
        "club_strength_score": 88.0,
        "national_team_strength_score": 80.0,
        "image_url": "/static/avatars/gianluigi-donnarumma.png",
        "stats": {
            "appearances": 38, "minutes_played": 3420, "goals": 0, "assists": 0,
            "shots_total": 0, "shots_on_target": 0, "pass_accuracy": 76.0,
            "key_passes": 0, "tackles": 0, "interceptions": 0, "clearances": 20,
            "blocks": 0, "saves": 85, "clean_sheets": 16, "goals_conceded": 32,
            "dribbles_completed": 0, "aerial_duels_won": 15, "fouls_committed": 1,
            "fouls_drawn": 3, "yellow_cards": 1, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "欧洲杯冠军", "honor_type": "national_team", "competition_name": "UEFA European Championship", "competition_weight": W["continental_cup"], "count": 1, "year": "2020"},
            {"honor_name": "法甲冠军", "honor_type": "club", "competition_name": "Ligue 1", "competition_weight": W["top5_league"], "count": 4, "year": "2025/2026"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 2, "year": "2025/2026"},
        ],
        "awards": [
            {"award_name": "雅辛奖", "award_weight": A["yashin_award"], "count": 1, "year": "2021"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 2, "year": "2025/2026"},
        ],
    },
    {
        "name": "曼努埃尔·诺伊尔",
        "name_en": "Manuel Neuer",
        "position": "goalkeeper",
        "nationality": "Germany",
        "age": 40,
        "market_value_euro": 4000000,
        "current_club": "Bayern Munich",
        "club_league": "Bundesliga",
        "is_captain": True,
        "is_vice_captain": False,
        "national_team": "Germany",
        "club_strength_score": 90.0,
        "national_team_strength_score": 85.0,
        "image_url": "/static/avatars/manuel-neuer.png",
        "stats": {
            "appearances": 28, "minutes_played": 2520, "goals": 0, "assists": 0,
            "shots_total": 0, "shots_on_target": 0, "pass_accuracy": 84.0,
            "key_passes": 2, "tackles": 0, "interceptions": 0, "clearances": 15,
            "blocks": 0, "saves": 70, "clean_sheets": 12, "goals_conceded": 26,
            "dribbles_completed": 0, "aerial_duels_won": 10, "fouls_committed": 1,
            "fouls_drawn": 2, "yellow_cards": 1, "red_cards": 0,
        },
        "honors": [
            {"honor_name": "世界杯冠军", "honor_type": "national_team", "competition_name": "FIFA World Cup", "competition_weight": W["world_cup"], "count": 1, "year": "2014"},
            {"honor_name": "欧冠冠军", "honor_type": "club", "competition_name": "UEFA Champions League", "competition_weight": W["champions_league"], "count": 2, "year": "2012/2013,2019/2020"},
            {"honor_name": "德甲冠军", "honor_type": "club", "competition_name": "Bundesliga", "competition_weight": W["top5_league"], "count": 12, "year": "2025/2026"},
            {"honor_name": "世俱杯冠军", "honor_type": "club", "competition_name": "FIFA Club World Cup", "competition_weight": W["club_world_cup"], "count": 2, "year": "2013,2020"},
        ],
        "awards": [
            {"award_name": "FIFA最佳门将", "award_weight": A["fifa_best_gk"], "count": 1, "year": "2014"},
            {"award_name": "赛季最佳阵容", "award_weight": A["team_of_season"], "count": 4, "year": "2013/2014"},
        ],
    },
]

SEASON = "2025/2026"


def get_mock_players():
    """Return the full list of mock players with 2025/26 season data."""
    return MOCK_PLAYERS


def compute_mock_data_hash() -> str:
    """计算 mock_data.py 文件内容的 SHA256，用于检测数据是否被手动修改过。"""
    file_path = os.path.abspath(__file__)
    with open(file_path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def seed_database():
    """将 mock player 数据写入数据库（会先清空旧数据再重新导入）。"""
    from ..models import Player, PlayerStats, PlayerHonor, PlayerAward
    from ..database import SessionLocal

    db = SessionLocal()
    try:
        # 清空旧数据：先删子表再删主表，避免外键依赖问题
        db.query(PlayerAward).delete()
        db.query(PlayerHonor).delete()
        db.query(PlayerStats).delete()
        db.query(Player).delete()
        db.commit()

        for p_data in MOCK_PLAYERS:
            # Create Player
            player = Player(
                name=p_data["name"],
                name_en=p_data["name_en"],
                position=p_data["position"],
                nationality=p_data["nationality"],
                age=p_data["age"],
                market_value_euro=p_data["market_value_euro"],
                current_club=p_data["current_club"],
                club_league=p_data["club_league"],
                is_captain=p_data["is_captain"],
                is_vice_captain=p_data["is_vice_captain"],
                national_team=p_data["national_team"],
                club_strength_score=p_data["club_strength_score"],
                national_team_strength_score=p_data["national_team_strength_score"],
                image_url=p_data.get("image_url", ""),
            )
            db.add(player)
            db.flush()  # get player.id

            # Create PlayerStats
            stats_data = p_data["stats"]
            stats = PlayerStats(
                player_id=player.id,
                season=SEASON,
                **stats_data,
            )
            db.add(stats)

            # Create honors
            for h in p_data.get("honors", []):
                honor = PlayerHonor(
                    player_id=player.id,
                    honor_name=h["honor_name"],
                    honor_type=h["honor_type"],
                    competition_name=h["competition_name"],
                    competition_weight=h["competition_weight"],
                    count=h.get("count", 1),
                    year=h.get("year", ""),
                )
                db.add(honor)

            # Create awards
            for a in p_data.get("awards", []):
                award = PlayerAward(
                    player_id=player.id,
                    award_name=a["award_name"],
                    award_weight=a["award_weight"],
                    count=a.get("count", 1),
                    year=a.get("year", ""),
                )
                db.add(award)

        db.commit()
        print(f"Seeded {len(MOCK_PLAYERS)} players to database.")
    finally:
        db.close()